package by.isysoi.dao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 */
@WebService(name = "BetDAO", targetNamespace = "http://dao.isysoi.by/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BetDAO {


    /**
     * @param arg0
     * @return returns java.util.List<by.isysoi.dao.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readWinnersByRace", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadWinnersByRace")
    @ResponseWrapper(localName = "readWinnersByRaceResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadWinnersByRaceResponse")
    @Action(input = "http://dao.isysoi.by/BetDAO/readWinnersByRaceRequest", output = "http://dao.isysoi.by/BetDAO/readWinnersByRaceResponse")
    List<Client> readWinnersByRace(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * @return returns java.util.List<by.isysoi.dao.Bet>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readBet", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadBet")
    @ResponseWrapper(localName = "readBetResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadBetResponse")
    @Action(input = "http://dao.isysoi.by/BetDAO/readBetRequest", output = "http://dao.isysoi.by/BetDAO/readBetResponse")
    List<Bet> readBet();

    /**
     * @param arg0
     * @return returns by.isysoi.dao.Bet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readBetById", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadBetById")
    @ResponseWrapper(localName = "readBetByIdResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadBetByIdResponse")
    @Action(input = "http://dao.isysoi.by/BetDAO/readBetByIdRequest", output = "http://dao.isysoi.by/BetDAO/readBetByIdResponse")
    Bet readBetById(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertBet", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.InsertBet")
    @ResponseWrapper(localName = "insertBetResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.InsertBetResponse")
    @Action(input = "http://dao.isysoi.by/BetDAO/insertBetRequest", output = "http://dao.isysoi.by/BetDAO/insertBetResponse")
    void insertBet(
            @WebParam(name = "arg0", targetNamespace = "")
                    Bet arg0);

}
