package by.isysoi.dao;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ClientDAOService", targetNamespace = "http://dao.isysoi.by/", wsdlLocation = "http://desktop-03g58vn:8080/Server_lab12_war_exploded/ClientDAOService?wsdl")
public class ClientDAOService
        extends Service {

    private final static URL CLIENTDAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTDAOSERVICE_EXCEPTION;
    private final static QName CLIENTDAOSERVICE_QNAME = new QName("http://dao.isysoi.by/", "ClientDAOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-03g58vn:8080/Server_lab12_war_exploded/ClientDAOService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTDAOSERVICE_WSDL_LOCATION = url;
        CLIENTDAOSERVICE_EXCEPTION = e;
    }

    public ClientDAOService() {
        super(__getWsdlLocation(), CLIENTDAOSERVICE_QNAME);
    }

    public ClientDAOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTDAOSERVICE_QNAME, features);
    }

    public ClientDAOService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTDAOSERVICE_QNAME);
    }

    public ClientDAOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTDAOSERVICE_QNAME, features);
    }

    public ClientDAOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientDAOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTDAOSERVICE_EXCEPTION != null) {
            throw CLIENTDAOSERVICE_EXCEPTION;
        }
        return CLIENTDAOSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns ClientDAO
     */
    @WebEndpoint(name = "ClientDAOPort")
    public ClientDAO getClientDAOPort() {
        return super.getPort(new QName("http://dao.isysoi.by/", "ClientDAOPort"), ClientDAO.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ClientDAO
     */
    @WebEndpoint(name = "ClientDAOPort")
    public ClientDAO getClientDAOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.isysoi.by/", "ClientDAOPort"), ClientDAO.class, features);
    }

}
