
package by.isysoi.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientDAO", targetNamespace = "http://dao.isysoi.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientDAO {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertClient", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.InsertClient")
    @ResponseWrapper(localName = "insertClientResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.InsertClientResponse")
    @Action(input = "http://dao.isysoi.by/ClientDAO/insertClientRequest", output = "http://dao.isysoi.by/ClientDAO/insertClientResponse")
    public void insertClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns by.isysoi.dao.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readClientById", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadClientById")
    @ResponseWrapper(localName = "readClientByIdResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadClientByIdResponse")
    @Action(input = "http://dao.isysoi.by/ClientDAO/readClientByIdRequest", output = "http://dao.isysoi.by/ClientDAO/readClientByIdResponse")
    public Client readClientById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<by.isysoi.dao.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readClients", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadClients")
    @ResponseWrapper(localName = "readClientsResponse", targetNamespace = "http://dao.isysoi.by/", className = "by.isysoi.dao.ReadClientsResponse")
    @Action(input = "http://dao.isysoi.by/ClientDAO/readClientsRequest", output = "http://dao.isysoi.by/ClientDAO/readClientsResponse")
    public List<Client> readClients();

}
