
package by.isysoi.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RaceDAOService", targetNamespace = "http://dao.isysoi.by/", wsdlLocation = "http://desktop-03g58vn:8080/Server_lab12_war_exploded/RaceDAOService?wsdl")
public class RaceDAOService
    extends Service
{

    private final static URL RACEDAOSERVICE_WSDL_LOCATION;
    private final static WebServiceException RACEDAOSERVICE_EXCEPTION;
    private final static QName RACEDAOSERVICE_QNAME = new QName("http://dao.isysoi.by/", "RaceDAOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-03g58vn:8080/Server_lab12_war_exploded/RaceDAOService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RACEDAOSERVICE_WSDL_LOCATION = url;
        RACEDAOSERVICE_EXCEPTION = e;
    }

    public RaceDAOService() {
        super(__getWsdlLocation(), RACEDAOSERVICE_QNAME);
    }

    public RaceDAOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RACEDAOSERVICE_QNAME, features);
    }

    public RaceDAOService(URL wsdlLocation) {
        super(wsdlLocation, RACEDAOSERVICE_QNAME);
    }

    public RaceDAOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RACEDAOSERVICE_QNAME, features);
    }

    public RaceDAOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RaceDAOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RaceDAO
     */
    @WebEndpoint(name = "RaceDAOPort")
    public RaceDAO getRaceDAOPort() {
        return super.getPort(new QName("http://dao.isysoi.by/", "RaceDAOPort"), RaceDAO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RaceDAO
     */
    @WebEndpoint(name = "RaceDAOPort")
    public RaceDAO getRaceDAOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.isysoi.by/", "RaceDAOPort"), RaceDAO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RACEDAOSERVICE_EXCEPTION!= null) {
            throw RACEDAOSERVICE_EXCEPTION;
        }
        return RACEDAOSERVICE_WSDL_LOCATION;
    }

}
